export const metadata = {
  title: "Privacy Policy | MJ Digital Services",
  description:
    "Privacy Policy for MJ Digital Services Private Limited — how we collect, use, and protect your information.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="blog-post-main blog-post-main-no-cover">
      <div className="blog-post-container" style={{ maxWidth: 860 }}>
        {/* Breadcrumb */}
        <div className="blog-post-breadcrumb">
          <a href="/" className="blog-post-breadcrumb-link">Home</a>
          <span>/</span>
          <span className="blog-post-breadcrumb-current">Privacy Policy</span>
        </div>

        {/* Title */}
        <h1 className="blog-post-title">Privacy Policy</h1>
        <div className="blog-post-meta">
          <span className="blog-post-meta-item">Last Updated: 22/06/2026</span>
        </div>

        {/* Content */}
        <div className="blog-post-content">
          <p>
            This Privacy Policy is an electronic record in terms of the Information
            Technology Act, 2000, the rules framed thereunder, and applicable amendments
            from time to time. This electronic record is generated by a computer system
            and does not require any physical or digital signatures.
          </p>

          <p>
            MJ Digital Services Private Limited, a company incorporated under the
            provisions of the Companies Act, 2013, having its Registered Office at D-19,
            FF, Abul Fazal Enclave Part-1, South Delhi, New Delhi &ndash; 110025 and
            Corporate Office at 7th Floor, AWFIS, Tower D, Bhutani Techno Park, Plot No.
            5, Sector 127, Noida, Uttar Pradesh &ndash; 201313, owns, operates and manages
            the website www.mjdigitalservices.com and related software platforms,
            applications, APIs, communication platforms, digital products, and technology
            services.
          </p>

          <h2>1. Our Commitment to Privacy</h2>
          <p>
            We value the trust placed in us and are committed to protecting user
            information. We do not sell or rent personal information and implement
            commercially reasonable safeguards to protect data.
          </p>

          <h2>2. Information We Collect</h2>
          <h3>Personal Information</h3>
          <ul>
            <li>Full Name</li>
            <li>Company Name</li>
            <li>Email Address</li>
            <li>Mobile Number</li>
            <li>Address</li>
            <li>GST Number</li>
            <li>PAN Number</li>
            <li>Aadhaar Number (where legally permitted)</li>
            <li>Business and KYC documents</li>
          </ul>

          <h3>Business Information</h3>
          <ul>
            <li>Company registration details</li>
            <li>Merchant information</li>
            <li>Billing and subscription information</li>
          </ul>

          <h3>Technical Information</h3>
          <ul>
            <li>IP Address</li>
            <li>Browser Type</li>
            <li>Device Information</li>
            <li>Operating System</li>
            <li>Usage Data</li>
            <li>Cookies and Log Files</li>
          </ul>

          <h2>3. Sources of Information</h2>
          <p>
            Information may be collected through registration forms, onboarding forms,
            support requests, emails, phone calls, KYC processes, API integrations and
            website usage.
          </p>

          <h2>4. Cookies</h2>
          <p>
            We use cookies and similar technologies to improve functionality, security
            and user experience.
          </p>

          <h2>5. How We Use Information</h2>
          <ul>
            <li>Service delivery</li>
            <li>Account management</li>
            <li>Customer support</li>
            <li>Security monitoring</li>
            <li>Fraud prevention</li>
            <li>Compliance obligations</li>
            <li>Product improvements</li>
            <li>Marketing communications</li>
          </ul>

          <h2>6. Information Sharing</h2>
          <p>
            Information may be shared with trusted service providers, cloud providers,
            telecom operators, payment gateways, regulators and authorities where legally
            required.
          </p>

          <h2>7. Data Security</h2>
          <p>
            We use SSL encryption, access controls, firewalls, monitoring systems and
            security procedures to protect information.
          </p>

          <h2>8. Data Retention</h2>
          <p>
            Information is retained as necessary for service delivery, legal compliance,
            fraud prevention and dispute resolution.
          </p>

          <h2>9. Third Party Websites</h2>
          <p>
            We are not responsible for privacy practices of third-party websites linked
            from our platforms.
          </p>

          <h2>10. Children&rsquo;s Privacy</h2>
          <p>Services are intended for users above 18 years of age.</p>

          <h2>11. Changes to This Policy</h2>
          <p>We reserve the right to amend this Privacy Policy at any time.</p>

          <h2>12. User Rights</h2>
          <p>
            Users may request access, correction, update or deletion of personal
            information subject to applicable laws.
          </p>

          <h2>13. Contact Details &amp; Grievance Officer</h2>
          <p>
            <strong>Registered Office</strong>
            <br />
            D-19, FF, Abul Fazal Enclave Part-1,
            <br />
            South Delhi, New Delhi &ndash; 110025
          </p>
          <p>
            <strong>Corporate Office</strong>
            <br />
            7th Floor, AWFIS, Tower D,
            <br />
            Bhutani Techno Park,
            <br />
            Plot No. 5, Sector 127,
            <br />
            Noida, Uttar Pradesh &ndash; 201313
          </p>
          <p>
            Support: <a href="mailto:support@mjdigitalservices.com">support@mjdigitalservices.com</a>
            <br />
            Privacy: <a href="mailto:privacy@mjdigitalservices.com">privacy@mjdigitalservices.com</a>
            <br />
            Grievance: <a href="mailto:grievance@mjdigitalservices.com">grievance@mjdigitalservices.com</a>
            <br />
            Business: <a href="mailto:business@mjdigitalservices.com">business@mjdigitalservices.com</a>
          </p>

          <h2>14. Applicable Law and Jurisdiction</h2>
          <p>
            This Privacy Policy shall be governed by the laws of India. Any disputes
            shall be subject to the exclusive jurisdiction of the competent courts located
            in Noida, Uttar Pradesh.
          </p>
        </div>

        <a href="/" className="blog-post-back">&larr; Back to Home</a>
      </div>
    </main>
  );
}