export const metadata = {
  title: "Terms & Conditions | MJ Digital Services",
  description:
    "Terms & Conditions governing the use of MJ Digital Services' website, products, APIs, and software services.",
};

export default function TermsOfServicePage() {
  return (
    <main className="blog-post-main blog-post-main-no-cover">
      <div className="blog-post-container" style={{ maxWidth: 860 }}>
        {/* Breadcrumb */}
        <div className="blog-post-breadcrumb">
          <a href="/" className="blog-post-breadcrumb-link">Home</a>
          <span>/</span>
          <span className="blog-post-breadcrumb-current">Terms &amp; Conditions</span>
        </div>

        {/* Title */}
        <h1 className="blog-post-title">Terms &amp; Conditions</h1>
        <div className="blog-post-meta">
          <span className="blog-post-meta-item">Last Updated: 22/06/2026</span>
        </div>

        {/* Content */}
        <div className="blog-post-content">
          <p>
            This Terms &amp; Conditions Agreement is an electronic record in terms of the
            Information Technology Act, 2000 and the applicable rules thereunder, as
            amended from time to time. This electronic record is generated by a computer
            system and does not require any physical or digital signatures.
          </p>

          <p>
            MJ Digital Services Private Limited, a company incorporated under the
            provisions of the Companies Act, 2013, having its Registered Office at D-19,
            FF, Abul Fazal Enclave Part-1, South Delhi, New Delhi &ndash; 110025 and
            Corporate Office at 7th Floor, AWFIS, Tower D, Bhutani Techno Park, Plot No.
            5, Sector 127, Noida, Uttar Pradesh &ndash; 201313 (hereinafter referred to as
            &ldquo;MJ Digital&rdquo;, &ldquo;Company&rdquo;, &ldquo;We&rdquo;,
            &ldquo;Our&rdquo; or &ldquo;Us&rdquo;), owns, operates and manages the website
            www.mjdigitalservices.com, related software applications, APIs, communication
            platforms, cloud infrastructure, mobile applications and digital products.
          </p>

          <p>
            By accessing, browsing, registering on, or using our Website, products, APIs,
            software platforms, applications, communication services, or any other
            services offered by MJ Digital, you agree to be bound by these Terms &amp;
            Conditions.
          </p>

          <h2>1. Definitions</h2>
          <p>For the purpose of these Terms:</p>
          <p>
            <strong>&ldquo;User&rdquo;</strong>, <strong>&ldquo;Customer&rdquo;</strong>,{" "}
            <strong>&ldquo;Client&rdquo;</strong>, <strong>&ldquo;Merchant&rdquo;</strong>,{" "}
            <strong>&ldquo;Partner&rdquo;</strong> or <strong>&ldquo;You&rdquo;</strong>{" "}
            means any individual, company, organization, developer, reseller,
            enterprise, merchant, or entity accessing or using the Company&rsquo;s
            services.
          </p>
          <p>
            <strong>&ldquo;Services&rdquo;</strong> shall include but not be limited to
            software development, website development, mobile application development,
            SaaS solutions, APIs, CPaaS services, AI solutions, cloud services,
            consulting services, fintech technology solutions and all related products
            offered by MJ Digital.
          </p>
          <p>
            <strong>&ldquo;Platform&rdquo;</strong> means the Website, APIs,
            applications, dashboards, portals, software systems and infrastructure
            operated by MJ Digital.
          </p>

          <h2>2. Services Offered</h2>
          <p>MJ Digital may provide the following services:</p>

          <h3>Software Development Services</h3>
          <ul>
            <li>ERP Development</li>
            <li>CRM Development</li>
            <li>HRMS Development</li>
            <li>SaaS Product Development</li>
            <li>Enterprise Software Solutions</li>
            <li>Custom Software Development</li>
          </ul>

          <h3>Web Development Services</h3>
          <ul>
            <li>Corporate Websites</li>
            <li>E-Commerce Websites</li>
            <li>Business Portals</li>
            <li>Custom Web Applications</li>
          </ul>

          <h3>Mobile Application Development</h3>
          <ul>
            <li>Android Applications</li>
            <li>iOS Applications</li>
            <li>Flutter Applications</li>
            <li>Hybrid Applications</li>
          </ul>

          <h3>API Services</h3>
          <ul>
            <li>Recharge APIs</li>
            <li>AEPS APIs</li>
            <li>BBPS APIs</li>
            <li>DMT APIs</li>
            <li>PAN APIs</li>
            <li>KYC APIs</li>
            <li>WhatsApp APIs</li>
            <li>SMS APIs</li>
            <li>RCS APIs</li>
            <li>Third-Party Integrations</li>
          </ul>

          <h3>CPaaS Solutions</h3>
          <ul>
            <li>WhatsApp Business Messaging</li>
            <li>Bulk SMS Services</li>
            <li>Transactional SMS Services</li>
            <li>Voice Solutions</li>
            <li>RCS Messaging Services</li>
          </ul>

          <h3>AI Solutions</h3>
          <ul>
            <li>AI Chatbots</li>
            <li>Voice AI Agents</li>
            <li>Customer Support Automation</li>
            <li>AI-Based Business Solutions</li>
          </ul>

          <h3>Cloud &amp; Infrastructure Services</h3>
          <ul>
            <li>Cloud Hosting</li>
            <li>Server Infrastructure</li>
            <li>Platform Management</li>
            <li>Managed Services</li>
          </ul>

          <p>
            The Company reserves the right to modify, suspend, discontinue, add, or
            remove any service without prior notice.
          </p>

          <h2>3. Eligibility</h2>
          <p>By using the Services, you represent and warrant that:</p>
          <ul>
            <li>You are at least 18 years of age.</li>
            <li>You are legally capable of entering into a binding agreement.</li>
            <li>
              Information submitted by you is true, accurate, complete and current.
            </li>
            <li>You shall comply with all applicable laws and regulations.</li>
          </ul>

          <h2>4. User Account Responsibilities</h2>
          <p>
            Users may be required to register and create accounts to access certain
            services.
          </p>
          <p>You agree that:</p>
          <ul>
            <li>Account credentials shall remain confidential.</li>
            <li>
              You are solely responsible for activities conducted through your account.
            </li>
            <li>
              You shall immediately notify MJ Digital of any unauthorized access.
            </li>
            <li>
              The Company shall not be liable for losses resulting from compromised
              credentials.
            </li>
          </ul>

          <h2>5. Acceptable Use of Services</h2>
          <p>Users shall not:</p>
          <ul>
            <li>Violate any applicable laws.</li>
            <li>Engage in fraudulent activities.</li>
            <li>Send spam, phishing or unsolicited communications.</li>
            <li>Use services for illegal gambling activities.</li>
            <li>Distribute malware, viruses, spyware or harmful code.</li>
            <li>Attempt unauthorized access to systems.</li>
            <li>Interfere with platform security.</li>
            <li>Reverse engineer, copy, modify or exploit proprietary software.</li>
            <li>Misuse APIs or exceed authorized limits.</li>
            <li>
              Engage in activities that may damage the reputation of MJ Digital.
            </li>
          </ul>
          <p>
            Violation of these provisions may result in immediate suspension or
            termination of services.
          </p>

          <h2>6. API Usage Terms</h2>
          <p>Where API services are provided:</p>
          <ul>
            <li>API keys must remain confidential.</li>
            <li>API credentials may not be shared with unauthorized parties.</li>
            <li>Users must comply with all integration guidelines.</li>
            <li>MJ Digital may apply rate limits and usage restrictions.</li>
            <li>Excessive or abusive API usage may result in suspension.</li>
            <li>
              API uptime is provided on a commercially reasonable basis and is not
              guaranteed.
            </li>
          </ul>
          <p>
            The Company reserves the right to revoke API access without prior notice in
            cases involving security concerns, abuse, fraud, or regulatory requirements.
          </p>

          <h2>7. Software Development Projects</h2>
          <p>
            For custom software, website, or application development projects:
          </p>
          <ul>
            <li>
              Project scope shall be governed by mutually agreed proposals, quotations,
              work orders or contracts.
            </li>
            <li>
              Timelines may vary based on project complexity and client responsiveness.
            </li>
            <li>
              Additional requirements beyond approved scope may incur additional
              charges.
            </li>
            <li>Delays caused by the client shall not constitute a breach by MJ Digital.</li>
          </ul>
          <p>
            Unless otherwise agreed in writing, ownership of deliverables shall transfer
            only after full payment of all applicable fees.
          </p>

          <h2>8. Payment Terms</h2>
          <p>Users agree to pay all applicable charges associated with services.</p>
          <h3>Payment Conditions</h3>
          <ul>
            <li>Invoices shall be payable as per agreed terms.</li>
            <li>Delayed payments may attract penalties or suspension.</li>
            <li>Taxes shall be payable as applicable under law.</li>
            <li>Subscription fees are generally payable in advance.</li>
          </ul>
          <p>The Company reserves the right to suspend services for overdue payments.</p>

          <h2>9. Refund Policy</h2>
          <p>
            Refunds shall be governed by the Company&rsquo;s Refund &amp; Cancellation
            Policy available separately on the Website.
          </p>
          <p>Generally, the following are non-refundable:</p>
          <ul>
            <li>Software Development Charges</li>
            <li>Website Development Charges</li>
            <li>Mobile App Development Charges</li>
            <li>Setup Fees</li>
            <li>Integration Charges</li>
            <li>Domain Registration Fees</li>
            <li>Hosting Charges</li>
            <li>Consultation Fees</li>
            <li>API Setup Charges</li>
            <li>WhatsApp Business Setup Charges</li>
          </ul>

          <h2>10. Intellectual Property Rights</h2>
          <p>All intellectual property rights relating to:</p>
          <ul>
            <li>Software</li>
            <li>APIs</li>
            <li>Source Code</li>
            <li>Documentation</li>
            <li>Designs</li>
            <li>Trademarks</li>
            <li>Logos</li>
            <li>Graphics</li>
            <li>Databases</li>
            <li>Content</li>
            <li>Business Processes</li>
          </ul>
          <p>shall remain the exclusive property of MJ Digital or its licensors.</p>
          <p>
            Nothing contained herein grants any ownership rights to users except where
            expressly agreed in writing.
          </p>

          <h2>11. Confidentiality</h2>
          <p>
            Users agree not to disclose any confidential information received from MJ
            Digital.
          </p>
          <p>Confidential information includes:</p>
          <ul>
            <li>Source Code</li>
            <li>Technical Documentation</li>
            <li>API Documentation</li>
            <li>Pricing Information</li>
            <li>Business Processes</li>
            <li>Security Procedures</li>
          </ul>
          <p>Confidentiality obligations shall survive termination of services.</p>

          <h2>12. Data Privacy</h2>
          <p>
            The collection, use, disclosure and processing of personal information shall
            be governed by the Company&rsquo;s Privacy Policy.
          </p>
          <p>By using the Services, users consent to such processing.</p>

          <h2>13. Third-Party Services</h2>
          <p>Certain services may rely on third-party providers including:</p>
          <ul>
            <li>Cloud Providers</li>
            <li>Telecom Operators</li>
            <li>Payment Gateways</li>
            <li>Messaging Providers</li>
            <li>Banking Partners</li>
            <li>Government Systems</li>
          </ul>
          <p>
            MJ Digital shall not be liable for failures, delays or interruptions caused
            by such third-party services.
          </p>

          <h2>14. Disclaimer of Warranties</h2>
          <p>
            Services are provided on an &ldquo;AS IS&rdquo; and &ldquo;AS
            AVAILABLE&rdquo; basis.
          </p>
          <p>MJ Digital does not warrant that:</p>
          <ul>
            <li>Services will be uninterrupted.</li>
            <li>Services will be error-free.</li>
            <li>Results obtained will be accurate.</li>
            <li>Defects will always be corrected immediately.</li>
          </ul>
          <p>
            All warranties not expressly stated herein are disclaimed to the fullest
            extent permitted by law.
          </p>

          <h2>15. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, MJ Digital shall not be liable for:
          </p>
          <ul>
            <li>Indirect Damages</li>
            <li>Consequential Losses</li>
            <li>Loss of Revenue</li>
            <li>Loss of Business</li>
            <li>Loss of Data</li>
            <li>Loss of Profits</li>
            <li>Reputational Damage</li>
          </ul>
          <p>
            In no event shall the Company&rsquo;s aggregate liability exceed the total
            amount paid by the Customer to MJ Digital during the three (3) months
            immediately preceding the event giving rise to the claim.
          </p>

          <h2>16. Force Majeure</h2>
          <p>
            MJ Digital shall not be liable for failure or delay in performance due to
            events beyond its reasonable control, including:
          </p>
          <ul>
            <li>Natural Disasters</li>
            <li>Floods</li>
            <li>Earthquakes</li>
            <li>Fire</li>
            <li>War</li>
            <li>Pandemic</li>
            <li>Government Restrictions</li>
            <li>Telecom Failures</li>
            <li>Internet Outages</li>
            <li>Cyber Attacks</li>
            <li>Utility Failures</li>
          </ul>

          <h2>17. Suspension and Termination</h2>
          <p>
            MJ Digital reserves the right to suspend or terminate services immediately
            if:
          </p>
          <ul>
            <li>These Terms are violated.</li>
            <li>Fraudulent activity is detected.</li>
            <li>Regulatory requirements demand suspension.</li>
            <li>Security risks are identified.</li>
            <li>Payment obligations remain unpaid.</li>
          </ul>
          <p>Termination shall not affect accrued rights or obligations.</p>

          <h2>18. Modifications to Terms</h2>
          <p>
            The Company reserves the right to update, modify or replace these Terms
            &amp; Conditions at any time.
          </p>
          <p>
            Continued use of services following such changes constitutes acceptance of
            the revised Terms.
          </p>

          <h2>19. Grievance Redressal</h2>
          <p>For any complaints, disputes or grievances, users may contact:</p>
          <p>
            <strong>Support Team</strong> Email:{" "}
            <a href="mailto:support@mjdigitalservices.com">support@mjdigitalservices.com</a>
          </p>
          <p>
            <strong>Grievance Officer</strong> Email:{" "}
            <a href="mailto:grievance@mjdigitalservices.com">grievance@mjdigitalservices.com</a>
          </p>
          <p>Operating Hours: Monday to Friday | 10:00 AM &ndash; 6:00 PM IST</p>

          <h2>20. Governing Law and Jurisdiction</h2>
          <p>
            These Terms &amp; Conditions shall be governed by and construed in
            accordance with the laws of India.
          </p>
          <p>
            Any dispute arising out of or relating to these Terms shall be subject to
            the exclusive jurisdiction of the competent courts situated at Noida, Uttar
            Pradesh, India.
          </p>
          <p>
            By using the Website and Services, you acknowledge that you have read,
            understood and agreed to these Terms &amp; Conditions.
          </p>
        </div>

        <a href="/" className="blog-post-back">&larr; Back to Home</a>
      </div>
    </main>
  );
}