export const metadata = {
  title: "Refund & Cancellation Policy | MJ Digital Services",
  description:
    "Refund & Cancellation Policy for MJ Digital Services — terms for cancellations, refunds, and payment disputes.",
};

export default function RefundPolicyPage() {
  return (
    <main className="blog-post-main blog-post-main-no-cover">
      <div className="blog-post-container" style={{ maxWidth: 860 }}>
        {/* Breadcrumb */}
        <div className="blog-post-breadcrumb">
          <a href="/" className="blog-post-breadcrumb-link">Home</a>
          <span>/</span>
          <span className="blog-post-breadcrumb-current">Refund &amp; Cancellation Policy</span>
        </div>

        {/* Title */}
        <h1 className="blog-post-title">Refund &amp; Cancellation Policy</h1>
        <div className="blog-post-meta">
          <span className="blog-post-meta-item">Last Updated: 22/06/2026</span>
        </div>

        {/* Content */}
        <div className="blog-post-content">
          <p>
            This Refund &amp; Cancellation Policy is an electronic record in terms of
            the Information Technology Act, 2000 and the applicable rules framed
            thereunder, as amended from time to time. This electronic record is
            generated by a computer system and does not require any physical or digital
            signatures.
          </p>

          <p>
            MJ Digital Services Private Limited, a company incorporated under the
            provisions of the Companies Act, 2013, having its Registered Office at D-19,
            FF, Abul Fazal Enclave Part-1, South Delhi, New Delhi &ndash; 110025 and
            Corporate Office at 7th Floor, AWFIS, Tower D, Bhutani Techno Park, Plot No.
            5, Sector 127, Noida, Uttar Pradesh &ndash; 201313 (hereinafter referred to
            as &ldquo;MJ Digital&rdquo;, &ldquo;Company&rdquo;, &ldquo;We&rdquo;,
            &ldquo;Our&rdquo; or &ldquo;Us&rdquo;), is committed to providing quality
            technology services and maintaining transparency in its refund and
            cancellation practices.
          </p>

          <p>
            By purchasing, subscribing to, registering for, or using any services
            offered by MJ Digital Services Private Limited, you acknowledge and agree to
            this Refund &amp; Cancellation Policy.
          </p>

          <h2>1. Purpose</h2>
          <p>
            The purpose of this Refund &amp; Cancellation Policy is to define the terms
            under which cancellations, refunds, service credits, and payment disputes
            shall be handled for products and services offered by MJ Digital.
          </p>
          <p>
            Due to the nature of software development, technology consulting, SaaS
            subscriptions, API services, communication services, cloud infrastructure,
            and digital solutions, refunds are subject to the conditions outlined
            herein.
          </p>

          <h2>2. Services Covered Under This Policy</h2>
          <p>
            This policy applies to all services offered by MJ Digital including but not
            limited to:
          </p>

          <h3>Software Development Services</h3>
          <ul>
            <li>Custom Software Development</li>
            <li>ERP Development</li>
            <li>CRM Development</li>
            <li>HRMS Development</li>
            <li>SaaS Product Development</li>
          </ul>

          <h3>Website Development Services</h3>
          <ul>
            <li>Corporate Websites</li>
            <li>E-Commerce Websites</li>
            <li>Web Portals</li>
            <li>Custom Web Applications</li>
          </ul>

          <h3>Mobile Application Development</h3>
          <ul>
            <li>Android Applications</li>
            <li>iOS Applications</li>
            <li>Flutter Applications</li>
            <li>Hybrid Applications</li>
          </ul>

          <h3>API Services</h3>
          <ul>
            <li>Recharge APIs</li>
            <li>AEPS APIs</li>
            <li>BBPS APIs</li>
            <li>DMT APIs</li>
            <li>PAN APIs</li>
            <li>KYC APIs</li>
            <li>WhatsApp APIs</li>
            <li>SMS APIs</li>
            <li>RCS APIs</li>
            <li>Third-Party Integrations</li>
          </ul>

          <h3>CPaaS Services</h3>
          <ul>
            <li>WhatsApp Business API</li>
            <li>Bulk SMS Services</li>
            <li>Transactional SMS Services</li>
            <li>Voice Services</li>
            <li>RCS Messaging Services</li>
          </ul>

          <h3>Cloud &amp; Infrastructure Services</h3>
          <ul>
            <li>Hosting Services</li>
            <li>Cloud Services</li>
            <li>Server Management</li>
            <li>Infrastructure Services</li>
          </ul>

          <h3>Consulting Services</h3>
          <ul>
            <li>Technology Consulting</li>
            <li>Business Consulting</li>
            <li>Digital Transformation Consulting</li>
          </ul>

          <h2>3. General Refund Policy</h2>
          <p>
            MJ Digital primarily provides customized and digital services that involve
            dedicated resources, development efforts, infrastructure costs, licensing
            fees, third-party costs, and implementation work.
          </p>
          <p>
            Accordingly, refunds are generally limited and subject to the specific terms
            outlined below.
          </p>
          <p>
            The Company reserves the sole right to determine refund eligibility after
            reviewing the nature of the service, work completed, contractual
            obligations, and circumstances of the request.
          </p>

          <h2>4. Non-Refundable Services</h2>
          <p>
            Unless expressly agreed otherwise in writing, the following payments are
            strictly non-refundable:
          </p>

          <h3>Development Services</h3>
          <ul>
            <li>Website Development Charges</li>
            <li>Mobile App Development Charges</li>
            <li>Software Development Charges</li>
            <li>UI/UX Design Charges</li>
            <li>Graphic Design Charges</li>
            <li>Custom Development Charges</li>
          </ul>

          <h3>Setup &amp; Implementation Charges</h3>
          <ul>
            <li>API Setup Fees</li>
            <li>Integration Charges</li>
            <li>Configuration Charges</li>
            <li>Deployment Charges</li>
            <li>Onboarding Fees</li>
            <li>Implementation Fees</li>
          </ul>

          <h3>Subscription Activation Charges</h3>
          <ul>
            <li>SaaS Setup Charges</li>
            <li>Platform Activation Fees</li>
            <li>Account Creation Fees</li>
            <li>Licensing Fees</li>
          </ul>

          <h3>Third-Party Services</h3>
          <ul>
            <li>Domain Registration Fees</li>
            <li>Domain Renewal Fees</li>
            <li>Hosting Charges</li>
            <li>SSL Certificate Charges</li>
            <li>Cloud Infrastructure Charges</li>
            <li>Server Procurement Charges</li>
          </ul>

          <h3>Communication Services</h3>
          <ul>
            <li>WhatsApp Business API Setup Charges</li>
            <li>Facebook Business Verification Charges</li>
            <li>SMS Header Registration Charges</li>
            <li>DLT Registration Charges</li>
            <li>Sender ID Charges</li>
            <li>Telecom Operator Charges</li>
          </ul>

          <h3>Professional Services</h3>
          <ul>
            <li>Consultancy Fees</li>
            <li>Advisory Fees</li>
            <li>Training Charges</li>
            <li>Technical Audit Fees</li>
          </ul>

          <p>
            No refund shall be granted once work has commenced or third-party expenses
            have been incurred.
          </p>

          <h2>5. Subscription Services</h2>
          <p>For subscription-based products and services:</p>
          <ul>
            <li>Customers may cancel future renewals at any time.</li>
            <li>Cancellation shall stop future billing only.</li>
            <li>Previously paid subscription fees are non-refundable.</li>
            <li>No partial refunds shall be issued for unused subscription periods.</li>
            <li>Services shall remain active until the end of the paid billing cycle.</li>
          </ul>

          <h2>6. Project Cancellation</h2>
          <h3>Cancellation by Customer</h3>
          <p>
            If a customer cancels a project after confirmation and commencement of
            work:
          </p>

          <h4>Before Project Initiation</h4>
          <p>
            If work has not started and no third-party costs have been incurred, the
            Company may consider a partial refund after deducting administrative
            charges.
          </p>

          <h4>After Project Initiation</h4>
          <p>If work has commenced:</p>
          <ul>
            <li>Advance payments shall generally be non-refundable.</li>
            <li>Completed milestones shall be billed in full.</li>
            <li>Any third-party expenses shall remain payable by the customer.</li>
          </ul>

          <h3>Cancellation by MJ Digital</h3>
          <p>MJ Digital reserves the right to cancel or suspend services where:</p>
          <ul>
            <li>Required information is not provided.</li>
            <li>The customer violates applicable laws.</li>
            <li>Fraudulent activity is suspected.</li>
            <li>Regulatory requirements prohibit continuation.</li>
            <li>Force majeure circumstances occur.</li>
          </ul>
          <p>
            In such cases, refund decisions shall be determined based on work completed
            and costs incurred.
          </p>

          <h2>7. Duplicate Payments</h2>
          <p>
            In the event a customer accidentally makes duplicate payments for the same
            service:
          </p>
          <ul>
            <li>The customer must notify MJ Digital immediately.</li>
            <li>Payment verification may be required.</li>
            <li>Verified duplicate payments shall be refunded.</li>
          </ul>
          <p>Refund Timeline: <strong>15 to 45 Business Days</strong>, subject to banking and payment gateway processing timelines.</p>

          <h2>8. Failed Transactions</h2>
          <p>
            Where a payment is debited from the customer account but the service is not
            activated due to technical reasons:
          </p>
          <ul>
            <li>The matter shall be investigated.</li>
            <li>
              Upon successful verification, the amount may either be refunded, or be
              adjusted against future services.
            </li>
          </ul>
          <p>
            Processing timelines may vary depending on the payment partner involved.
          </p>

          <h2>9. Service Non-Delivery</h2>
          <p>
            If MJ Digital is unable to provide a purchased service solely due to reasons
            attributable to the Company, the Company may at its sole discretion:
          </p>
          <ul>
            <li>Provide a Full Refund</li>
            <li>Provide a Partial Refund</li>
            <li>Offer Service Credits</li>
            <li>Offer Alternative Services</li>
          </ul>
          <p>The Company&rsquo;s decision shall be final and binding.</p>

          <h2>10. Refund Exclusions</h2>
          <p>Refunds shall not be granted for:</p>
          <ul>
            <li>Change of mind</li>
            <li>Lack of usage</li>
            <li>Business losses</li>
            <li>Market conditions</li>
            <li>User negligence</li>
            <li>Customer-side technical issues</li>
            <li>Delays caused by customer non-cooperation</li>
            <li>Delays caused by third-party providers</li>
            <li>Government restrictions</li>
            <li>Regulatory changes</li>
            <li>Internet or telecom outages</li>
            <li>Force majeure events</li>
          </ul>

          <h2>11. Chargebacks &amp; Payment Disputes</h2>
          <p>
            Customers are encouraged to contact MJ Digital before initiating any
            chargeback or payment dispute.
          </p>
          <p>If a chargeback is initiated:</p>
          <ul>
            <li>Services may be suspended immediately.</li>
            <li>Ongoing projects may be halted.</li>
            <li>Access to platforms may be restricted.</li>
            <li>Additional documentation may be requested.</li>
          </ul>
          <p>
            Fraudulent or abusive chargebacks may result in permanent termination of
            services.
          </p>

          <h2>12. Refund Process</h2>
          <p>To request a refund, customers must submit a written request containing:</p>
          <ul>
            <li>Full Name</li>
            <li>Company Name</li>
            <li>Registered Email Address</li>
            <li>Invoice Number</li>
            <li>Transaction ID</li>
            <li>Service Purchased</li>
            <li>Reason for Refund Request</li>
            <li>Supporting Documentation (if applicable)</li>
          </ul>
          <p>Refund requests may be submitted to:</p>
          <p>
            <strong>Accounts Department</strong>
            <br />
            Email: <a href="mailto:accounts@mjdigitalservices.com">accounts@mjdigitalservices.com</a>
            <br />
            CC: <a href="mailto:support@mjdigitalservices.com">support@mjdigitalservices.com</a>
          </p>

          <h2>13. Refund Timelines</h2>
          <p>Upon approval:</p>
          <table>
            <thead>
              <tr>
                <th>Refund Method</th>
                <th>Estimated Processing Time</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>UPI</td>
                <td>3 &ndash; 7 Business Days</td>
              </tr>
              <tr>
                <td>Net Banking</td>
                <td>5 &ndash; 10 Business Days</td>
              </tr>
              <tr>
                <td>Credit Card</td>
                <td>7 &ndash; 15 Business Days</td>
              </tr>
              <tr>
                <td>Debit Card</td>
                <td>7 &ndash; 15 Business Days</td>
              </tr>
              <tr>
                <td>Bank Transfer</td>
                <td>5 &ndash; 10 Business Days</td>
              </tr>
            </tbody>
          </table>
          <p>
            Actual timelines may vary depending on banking institutions and payment
            gateway partners.
          </p>

          <h2>14. Limitation of Liability</h2>
          <p>
            Approval of any refund shall not be construed as an admission of fault or
            liability by MJ Digital.
          </p>
          <p>
            The Company&rsquo;s total liability in connection with any refund claim
            shall not exceed the amount actually received by MJ Digital for the relevant
            service.
          </p>

          <h2>15. Modifications to This Policy</h2>
          <p>
            MJ Digital reserves the right to amend, modify, update, or replace this
            Refund &amp; Cancellation Policy at any time without prior notice.
          </p>
          <p>The latest version shall always be available on the Company&rsquo;s Website.</p>
          <p>
            Continued use of services after such modifications constitutes acceptance
            of the revised policy.
          </p>

          <h2>16. Contact Details</h2>
          <p>
            <strong>Registered Office</strong>
            <br />
            D-19, FF, Abul Fazal Enclave Part-1
            <br />
            South Delhi
            <br />
            New Delhi &ndash; 110025
          </p>
          <p>
            <strong>Corporate Office</strong>
            <br />
            7th Floor, AWFIS, Tower D
            <br />
            Bhutani Techno Park
            <br />
            Plot No. 5, Sector 127
            <br />
            Noida, Uttar Pradesh &ndash; 201313
          </p>
          <p>
            <strong>Accounts Department</strong>:{" "}
            <a href="mailto:accounts@mjdigitalservices.com">accounts@mjdigitalservices.com</a>
            <br />
            <strong>Customer Support</strong>:{" "}
            <a href="mailto:support@mjdigitalservices.com">support@mjdigitalservices.com</a>
            <br />
            <strong>Business Enquiries</strong>:{" "}
            <a href="mailto:business@mjdigitalservices.com">business@mjdigitalservices.com</a>
          </p>
          <p>Operating Hours: Monday to Friday | 10:00 AM &ndash; 6:00 PM IST</p>

          <h2>17. Governing Law and Jurisdiction</h2>
          <p>
            This Refund &amp; Cancellation Policy shall be governed by and interpreted
            in accordance with the laws of India.
          </p>
          <p>
            Any dispute arising out of or relating to this Policy shall be subject to
            the exclusive jurisdiction of the competent courts situated in Noida, Uttar
            Pradesh, India.
          </p>
          <p>
            By using the Company&rsquo;s services, you acknowledge that you have read,
            understood, and agreed to this Refund &amp; Cancellation Policy.
          </p>
        </div>

        <a href="/" className="blog-post-back">&larr; Back to Home</a>
      </div>
    </main>
  );
}